DROP TABLE IF EXISTS stripe_sources;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS stripe;
DROP TABLE IF EXISTS amazon;
DROP TABLE IF EXISTS paypal;
DROP TABLE IF EXISTS bitpay;
